# Generated by Django 5.1.3 on 2024-11-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_address', models.CharField(max_length=200)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_address', models.CharField(max_length=200)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('weight', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
                ('shipping_type', models.CharField(max_length=100)),
                ('origin_office', models.CharField(max_length=100)),
                ('destination_office', models.CharField(max_length=100)),
                ('shipping_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('booking_mode', models.CharField(max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
