# Generated by Django 5.1.3 on 2024-11-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_shipment_options_shipment_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='liveupdate',
            name='shipment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='live_update', to='account.shipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liveupdate',
            name='stages_label',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Withheld', 'Withheld')], default='Dispatched', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liveupdate',
            name='stages_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed Stage', 'Completed Stage'), ('Withheld stage', 'Withheld stage')], default='Active', max_length=50),
            preserve_default=False,
        ),
    ]
