# Generated by Django 5.1.3 on 2024-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_shipment_options_liveupdate_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdate',
            name='stages_status',
            field=models.CharField(choices=[('active', 'active'), ('complete', 'complete'), ('blocked', 'blocked')], max_length=50),
        ),
    ]
