# Generated by Django 5.1.3 on 2024-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_liveupdate_stages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='amount_paid',
            field=models.CharField(max_length=100),
        ),
    ]
