# Generated by Django 4.2 on 2024-12-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_shipment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdate',
            name='stages_status',
            field=models.CharField(choices=[('complete', 'complete'), ('blocked', 'blocked')], max_length=50),
        ),
    ]
